<html>
    <head></head>
    <body>
        <p>Kedves $user.name$!</p>
        <br/>
        <p>Valaki új jelszót igényelt ehhez a felhasználóhoz.</p>
        <p>Ha nem Ön igényelte, akkor ezt az üzenetet nyugodtan figyelmen kívül hagyhatja.</p>
        <br/>
        <p>Az új jelszó megadásához kattintson az alábbi linkre:</p>
        <a href="$url$">$url$</a>
        <br/>
        <p>Ez a link 24 óráig aktív, utána újra kell igényelni a jelszó-visszaállítást.</p>

        <br/><br/>
        <p>Üdvözlettel:</p>
        <p>Borostack Webshop</p>
    </body>
</html>