
export const DO_NOTHING = "DO_NOTHING";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_CATEGORIES_IN_PROGRESS = "FETCH_CATEGORIES_IN_PROGRESS";
export const ADD_CATEGORY = "ADD_CATEGORY";
