export const REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const DO_NOTHING = "DO_NOTHING";
export const RESET = "RESET";
