export const CATEGORY = "CATEGORY";
export const PRODUCT = "PRODUCT";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const RESPONSE_MESSAGE = "RESPONSE_MESSAGE";
export const CURRENT_USER = "CURRENT_USER";